data:
  image: busybox
  volumes:
    - /mnt/storage/tmp:/mnt/tmp:rw
    - /mnt/storage/downloads:/mnt/downloads:rw
    - /mnt/complete:/mnt/complete:rw

sonarr:
  image: tuxeh/sonarr
  restart: always
  dns:
    - 192.168.1.1
    - 8.8.8.8
    - 8.8.4.4
  expose:
    - "8989"
  ports:
    - "8989:8989"
  user: "root"
  volumes:
    - /mnt/storage/downloads:/volumes/completed:rw
    - /mnt/storage/dockerdata/sonarr:/volumes/config:rw
    - /mnt/complete:/volumes/media:rw
  links:
    - sabnzbd

radarr:
  image: linuxserver/radarr
  restart: always
  dns:
    - 192.168.1.1
    - 8.8.8.8
    - 8.8.4.4
  expose:
    - "7878"
  ports:
    - "7878:7878"
  environment:
    - PUID=1000
    - PGID=1000
  volumes:
    - /mnt/storage/downloads:/mnt/downloads:rw
    - /mnt/storage/dockerdata/radarr:/config:rw
    - /mnt/complete/Movies:/movies:rw
  links:
    - sabnzbd
    - deluge

deluge:
  build: deluge
  restart: always
  dns:
    - 192.168.1.1
    - 8.8.8.8
    - 8.8.4.4
  expose:
    - "58846"
    - "8112"
    - "53160"
    - "53160/udp"
  ports:
    - "58846:58846"
    - "8112:8112"
  volumes_from:
    - data
  volumes:
    - /mnt/storage/dockerdata/deluge:/mnt/state:rw

headphones:
  build: headphones
  restart: always
  dns:
    - 192.168.1.1
    - 8.8.8.8
    - 8.8.4.4
  expose:
    - "8181"
  ports:
    - "8181:8181"
  volumes_from:
    - data
  volumes:
    - /mnt/storage/dockerdata/headphones:/mnt/state:rw
  links:
    - sabnzbd

sabnzbd:
  build: sabnzbd
  restart: always
  dns:
    - 192.168.1.1
    - 8.8.8.8
    - 8.8.4.4
  expose:
    - "8080"
  ports:
    - "8080:8080"
  volumes_from:
    - data
  volumes:
    - /mnt/storage/dockerdata/sabnzbd:/mnt/state:rw

file-watcher:
  image: jsturgis/node-file-watcher:1.0.5
  user: jeff
  restart: always
  env_file: node-file-watcher.env
  volumes:
    - /mnt/complete:/mnt/src:rw
    - /home/ec2-user/media-server-dockerfiles/file-watcher:/.ssh 
  environment:
    - watchedDir=/mnt/src
    - destPath=/mnt/store
    - useSsh=true
    - certPath=/.ssh/id_rsa
